server:
  http2:
    enabled: true
  ssl:
    key-store: file:///C:/Users/sxs/projects/IdeaProjects/demo/taco-cloud/mykeys.jks
    key-store-password: letmein
    key-password: letmein
  port: 8443

spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 1d5b6b02971489b180a7
            clientSecret: f972d3e3c004bd50bf2ac970d513f19a56bebc49
            scope: user,user:email
  data:
    rest:
      base-path: /api
#      default-media-type: application/json
logging:
  level:
    root: debug
taco:
  orders:
    page-size: 10