server:
  port: 9010

spring:
  security:
    oauth2:
      client:
        provider:
          tacocloud:
            #            issuer-uri: http://authserver:9000
            authorization-uri: http://authserver:9000/oauth2/authorize
            token-uri: http://authserver:9000/oauth2/token
            jwk-set-uri: http://authserver:9000/oauth2/jwks
            user-info-uri: http://authserver:9000/userinfo
            user-name-attribute: sub
        registration:
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            clientName: server
            authorization-grant-type: authorization_grant
            redirect-uri: "http://127.0.0.1:9010/login/oauth2/code/{registrationId}"
            scope:
              - writeIngredients
              - deleteIngredients
              - openid
logging:
  level:
    root: trace